package util

const (
	RoleKey                       string = "ROLE#"
	SuperAdminKey                 string = "SUPER_ADMIN#"
	TenantKey                     string = "TENANT#"
	HospitalKey                   string = "HOSPITAL#"
	DoctorKey                     string = "DOCTOR#"
	ReceptionistKey               string = "RECEPTIONIST#"
	NurseKey                      string = "NURSE#"
	PharamacistKey                string = "PHARMACIST#"
	PatientKey                    string = "PATIENT#"
	MedicinesKey                  string = "MEDICINES#"
	MedicalRecordKey              string = "MEDICAL_RECORD#"
	AppointmentKey                string = "APPOINTMENT#"
	PrescriptionKey               string = "PRESCRIPTION#"
	TestKey                       string = "TEST#"
	TestReportKey                 string = "TEST_REPORT#"
	BillKey                       string = "BILL#"
	GuardianKey                   string = "GUARDIAN#"
	ConsentKey                    string = "CONSENT#"
	SuperAdminCollection          string = "SUPERADMIN"
	TenantCollection              string = "TENANT"
	HospitalCollection            string = "HOSPITAL"
	DoctorCollection              string = "DOCTOR"
	DoctorTimeSlotCollection      string = "DOCTOR_TIMESLOTS"
	ReceptionistCollection        string = "RECEPTIONIST"
	PatientCollection             string = "PATIENT"
	MedicalRecordCollection       string = "MEDICAL_RECORD"
	NurseCollection               string = "NURSE"
	MedicineCollection            string = "MEDICINES"
	AppointmentCollection         string = "APPOINTMENT"
	TestReportCollection          string = "TEST_REPORT"
	TestCollection                string = "TEST"
	PharmacistCollection          string = "PHARMACIST"
	PrescriptionCollection               = "PRESCRIPTION"
	RoleCollection                       = "ROLE"
	BillCollection                       = "BILL"
	GuardianCollection                   = "GUARDIAN"
	ConsentCollection                    = "CONSENT"
	ConsentVerificationCollection        = "CONSENT_VERIFICATION"
)
